name: FOOO

on:
  workflow_dispatch:
env:
  OUTER: outer env

jobs:
  demo:
    name: Print Env
    env:
      ENVRUN: env run
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        env:
          STEPS: steps env
        run: |
          echo "steps print : $STEPS"
          echo "demo print : $ENVRUN"
          echo "outer print : $OUTER"
          echo foo=fooooooooo
          echo "Foo is : $foo"
      - name: step-2
        run: |
          echo "Foo is : @foo"
