name: FOOO

on:
  workflow_dispatch:
env:
  OUTER: outer env

jobs:
  demo:
    name: Print Env
    env:
      ENVRUN: env run
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        id: first
        env:
          STEPS: steps env
        run: |
          foo=fooooo

          echo "steps print : $STEPS"
          echo "demo print : $ENVRUN"
          echo "outer print : $OUTER"

          echo "foo=secret fooo" >> $GITHUB_OUTPUT
          echo "FOO=fooooo secret" >> $GITHUB_ENV

          echo "Foo is : $foo"
          echo "Foo is : $FOO"
      - name: step-2
        run: |
          echo "Foo is : $FOO"
          echo "Foo is : ${{ steps.first.outputs.foo }}"
