name: This is ENV Dude

on:
  workflow_dispatch:
env:
  OUTER: outer env

jobs:
  env-run:
    name: Print Env
    env:
      ENVRUN: env run
    runs-on: ubuntu-latest
    steps:
      - name: Print Steps
        env:
          STEPS: steps env
        run: |
          echo "steps print : $STEPS"
          echo "env-run print : $ENVRUN"
          echo "outer print : $OUTER"
