name: Demo

on: workflow_dispatch

jobs:
  test:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Print all
        run: |
          echo "Repo Secret: ${{ secrets.REPO_SECRET }}"
          echo "Repo Variable: ${{ vars.REPO_VARIABLE }}"
          echo "Env Secret: ${{ secrets.SECRET_ENVIRONMENT }}"
          echo "Env Variable: ${{ vars.ENVIRONMENT_VARIABLES }}"
